Portfolio setup and mobile first-Feature 1
MANYIKAM/Portfolio-setup-and-mobile-first pull request #1
Opened 2022-09-21 22:03 UTC by MANYIKAM

My Portfolio setup and mobile first.
The following were done during this session
1. Set up of the Repo
2. Readme file has been created and updated inline with the project
3. Html file has been developed as per the requirement of having the first two sections
4. Css style sheet has been created and updated accordingly
5. Linters errors has been  done

2022-09-21 22:19 UTC, GiuseppeTG requested changes
Hi @MANYIKAM  👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ 

You have submitted a project, that has not properly set up linters. As you can see, in this PR linters checkers are not running. 
You need to have this folder structure for your linters: 
- .github > workflows > linters.yml

Please check the [Microverse Linters](https://github.com/microverseinc/linters-config) repo for more information 🤓 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-22 06:33 UTC, frank1738 requested changes
Hi @MANYIKAM , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![YesYouAreGIF (2)](https://user-images.githubusercontent.com/50941074/172881298-64e98170-87c5-4075-8a77-71d65d991f55.gif)


## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay
✅Good PR summary👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 06:33 UTC, frank1738 commented on index.html
> +        <h1 class="log">Manyikam</h1>
- [ ] Kindly wrap your logo in an `<a>` tag. This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info

2022-09-22 06:33 UTC, frank1738 commented on index.html
> +</section>
- [ ] Kindly Provide your design with background images to match the Figma design
### Your Desin

![image](https://user-images.githubusercontent.com/98453979/191673823-5edbd42c-706f-4614-ad99-db19265be4ed.png)

### Figma Design

![image](https://user-images.githubusercontent.com/98453979/191674024-e3afdf1c-2c91-4c94-86d8-3f22ddf3edf7.png)

- [ ] Kindly space your social icons to ensure proper spacing of elements to match the Figma design

![image](https://user-images.githubusercontent.com/98453979/191674372-2737b025-7dba-493f-8abf-d444ee620c18.png)

### Check Figma

![image](https://user-images.githubusercontent.com/98453979/191674483-31b02d83-57db-4825-98b6-468bd109be76.png)

2022-09-22 13:14 UTC, jasonfelice requested changes
Hi @MANYIKAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
- [ ] Please make sure the linter checks are running and there are no errors.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 13:14 UTC, jasonfelice commented on index.html
> +     <div class="flexbox">
- [ ] Kindly use `ul` to group social links.
- [ ] The social links don't look like the Figma design. Please fix that.
![image](https://user-images.githubusercontent.com/92215878/191754538-8590dcab-697e-4ae4-be4a-d83cf3fef614.png)

2022-09-22 13:14 UTC, jasonfelice commented on Style.css
> +}
- [ ] The design doesn't look like the given Figma template. Kindly remove the background from the `body`, and use it on appropriate section(s). 😄 
![image](https://user-images.githubusercontent.com/92215878/191755169-2b2a4783-3ce1-4028-882c-1df282dfd97b.png)

## Figma Design:
![image](https://user-images.githubusercontent.com/92215878/191755426-a12e5d88-3680-4874-9ba4-9f1b6fb8796a.png)

2022-09-22 13:14 UTC, jasonfelice commented on index.html
> +    <h2><a class="social-media" href="#">LET’S CONNECT</a></h2>
- [ ] Let's use proper style and color for this link. Please refer to the [Figma Template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122).

2022-09-22 22:32 UTC, isaacpitwa approved these changes
# Approved 💯 ✅ 🥳 🎈 🎉 

Hi @MANYIKAM   👋🏻 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

## Highlights ✅ 
Highly organized and clean code ✔️ 👨🏻‍💻 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 


## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Check the comments under the review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 04:40 UTC, merged

2022-09-23 04:41 UTC, MANYIKAM commented
Portfolio Setup and mobile first -feature1 merging with the main 

- Html file has been updated with all required changes
- Css file has been updated accordingly with few changes
- Linters has been set up as per the requirement