Mobile menu2
MANYIKAM/Portfolio-setup-and-mobile-first pull request #10
Opened 2022-10-19 14:57 UTC by MANYIKAM

- [ ] Changes made as per the review
- [ ] Color added
- [ ] Padding adjusted
- [ ] height increased

2022-10-19 15:38 UTC, KayLemba requested changes
Hi @MANYIKAM  👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.
 
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-19 15:38 UTC, KayLemba commented on Index.js
> +document.querySelector('.nav-menu .hamburger').addEventListener('click', () => {
As Requested by  the previous 
<ul class="contains-task-list" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px !important; margin-bottom: 16px; position: relative; list-style-type: none; color: rgb(173, 186, 199); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(34, 39, 46); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li class="task-list-item" style="box-sizing: border-box; list-style-type: none;"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" style="box-sizing: border-box; font: inherit; margin: 0px 0.2em 0.25em -1.6em; overflow: visible; padding: 0px; vertical-align: middle;"><span> </span>Please remove this top white header section<span> </span><g-emoji class="g-emoji" alias="arrow_down" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2b07.png" style="box-sizing: border-box; display: inline-block; min-width: 1ch; font-family: &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 1em; font-weight: 400; line-height: 1; vertical-align: -0.075em; font-style: normal !important;">⬇️</g-emoji><span> </span>When the user clicks (or taps) the hamburger button, only the mobile menu shoup be displayed. Let's give a 100% of height to your mobile menu to prevent that</li></ul><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(173, 186, 199); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(34, 39, 46); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/79058364/196702117-5eef11b1-c233-41d1-8b71-9ab8a7aa20de.png" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;"><img src="https://user-images.githubusercontent.com/79058364/196702117-5eef11b1-c233-41d1-8b71-9ab8a7aa20de.png" alt="Screenshot from 2022-10-19 15-16-06" style="box-sizing: content-box; border-style: none; max-width: 100%; background-color: var(--color-canvas-default);"></a></p><ul class="contains-task-list" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; position: relative; list-style-type: none; color: rgb(173, 186, 199); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(34, 39, 46); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li class="task-list-item" style="box-sizing: border-box; list-style-type: none;"><p dir="auto" style="box-sizing: border-box; margin-top: 16px; margin-bottom: 16px;"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" style="box-sizing: border-box; font: inherit; margin: 0px 0.2em 0.25em -1.6em; overflow: visible; padding: 0px; vertical-align: middle;"><span> </span>Great job so far<span> </span><g-emoji class="g-emoji" alias="raised_hands" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f64c.png" style="box-sizing: border-box; display: inline-block; min-width: 1ch; font-family: &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 1em; font-weight: 400; line-height: 1; vertical-align: -0.075em; font-style: normal !important;">🙌</g-emoji><span> </span>however according to the project requirements. 


Please change the blue background color of your mobile menu page instead used the one provided in the Figma template<span> </span><code class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">background: #6070FF;</code>. This will make your website similar to the original design.<span> </span><g-emoji class="g-emoji" alias="100" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4af.png" style="box-sizing: border-box; display: inline-block; min-width: 1ch; font-family: &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 1em; font-weight: 400; line-height: 1; vertical-align: -0.075em; font-style: normal !important;">💯</g-emoji><span> </span><g-emoji class="g-emoji" alias="1st_place_medal" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f947.png" style="box-sizing: border-box; display: inline-block; min-width: 1ch; font-family: &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 1em; font-weight: 400; line-height: 1; vertical-align: -0.075em; font-style: normal !important;">🥇</g-emoji></p></li><li class="task-list-item" style="box-sizing: border-box; list-style-type: none; margin-top: 4px;"><p dir="auto" style="box-sizing: border-box; margin-top: 16px; margin-bottom: 16px;"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" style="box-sizing: border-box; font: inherit; margin: 0px 0.2em 0.25em -1.6em; overflow: visible; padding: 0px; vertical-align: middle;"><span> </span>Nice implementing the design, however, it would be better if you add a little bit of blur to your overlay in order to match the Figma design and also make a good contrast<span> </span><g-emoji class="g-emoji" alias="art" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f3a8.png" style="box-sizing: border-box; display: inline-block; min-width: 1ch; font-family: &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 1em; font-weight: 400; line-height: 1; vertical-align: -0.075em; font-style: normal !important;">🎨</g-emoji><span> </span>👨🏻‍🎨</p></li><li class="task-list-item" style="box-sizing: border-box; list-style-type: none; margin-top: 4px;"><p dir="auto" style="box-sizing: border-box; margin-top: 16px; margin-bottom: 16px;"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" style="box-sizing: border-box; font: inherit; margin: 0px 0.2em 0.25em -1.6em; overflow: visible; padding: 0px; vertical-align: middle;"><span> </span>What about preventing the sub-background from scrolling when the navbar is open? You can use a CSS property<span> </span><code class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">over-flow: hidden;</code><s [...]

2022-10-19 19:45 UTC, Ismailco requested changes
### Hi @MANYIKAM, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-19 19:45 UTC, Ismailco commented on index.html
> +            </div>
- [ ] As the previous reviewer mentioned kindly consider adding a little bit of blur to your overlay in order to match the Figma design and also make a good contrast
- [ ] As the previous reviewer suggest kindly reduce the margin/padding between the navigation links so it looks like the Figma design
- [ ] [OPTIONAL] Kindly consider using the same font width and font size as the Figma design, this will make your Fonts match the provided design

![Screenshot_20221019_204352](https://user-images.githubusercontent.com/25227022/196788743-1712970b-c44e-4b00-9ffd-2cd33879fb71.png)

2022-10-20 09:59 UTC, omarsalem7 requested changes
Hi @MANYIKAM, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![Almost near](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✔️ All linter checks pass
✔️ Descriptive pull request

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 09:59 UTC, omarsalem7 commented on index.html
> +              x
- [ ] As the previous reviewer mentioned, kindly consider adding blur to the mobile menu to match it like the Figma design. You can add this property to add blur effect `backdrop-filter: blur(7px);`

2022-10-20 10:33 UTC, MANYIKAM commented
Good day

I do not understand now on where am i wrong attached is my screen print
from my system

On Wed, Oct 19, 2022 at 5:38 PM Kalolo Chola Lemba ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @MANYIKAM <https://github.com/MANYIKAM> 👋
> Good job so far working on the project requirements!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
> To Highlight 🎉
> No linter errors. ✔️
> GitHub flow is followed. ✔️
>
> Required Changes ♻️
> Check the comments under the review in the inline comments.
>
> Optional suggestions
> Every comment with the [OPTIONAL] prefix is not crucial enough to stop the
> approval of this PR. However, I strongly recommend you to take them into
> account as they can make your code better.
>
> You can also consider:
> N/A
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.
>
> As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have
> a limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.
> ------------------------------
>
> In Index.js
> <https://github.com/MANYIKAM/Portfolio-setup-and-mobile-first/pull/10#discussion_r999629775>
> :
>
> > @@ -0,0 +1,13 @@
>
> +document.querySelector('.nav-menu .hamburger').addEventListener('click', () => {
>
>
> As Requested by the previous
>
>    -  Please remove this top white header section ⬇️ When the user clicks
>    (or taps) the hamburger button, only the mobile menu shoup be displayed.
>    Let's give a 100% of height to your mobile menu to prevent that
>
> [image: Screenshot from 2022-10-19 15-16-06]
> <https://user-images.githubusercontent.com/79058364/196702117-5eef11b1-c233-41d1-8b71-9ab8a7aa20de.png>
>
>    -
>
>     Great job so far 🙌 however according to the project requirements.
>
>    Please change the blue background color of your mobile menu page
>    instead used the one provided in the Figma template background:
>    #6070FF;. This will make your website similar to the original design.
>    💯 🥇
>    -
>
>     Nice implementing the design, however, it would be better if you add
>    a little bit of blur to your overlay in order to match the Figma design and
>    also make a good contrast 🎨 👨🏻‍🎨
>    -
>
>     What about preventing the sub-background from scrolling when the
>    navbar is open? You can use a CSS property over-flow: hidden; to do
>    that, which will make your mobile menu correspond to the original design.
>    💯 🥇
>    -
>
>    Adding these features will make your design look great and look
>    exactly like the Figma design, I highly recommend you do this in the
>    meantime, I'll approve this project since the previous reviewer is skipping
>    this.
>
> Your design:
>
> [image: design 1]
> <https://user-images.githubusercontent.com/79506105/196736937-41910235-5fa5-4e53-a952-a02924d39cc5.png>
>
> Please stick to this Figma design:
>
> [image: menu figma]
> <https://user-images.githubusercontent.com/79506105/196737191-d87569e2-349d-4413-8f8c-40f342850d30.png>
>
> It would be nice if you paid more attention to detail. Your Portfolio is
> supposed to be similar to the template you picked.
>
> Please remove this top white header section ⬇️ When the user clicks (or
> taps) the hamburger button, only the mobile menu shoup be displayed. Let's
> give a 100% of height to your mobile menu to prevent that
> Screenshot from 2022-10-19 15-16-06
>
> Great job so far 🙌 however according to the project requirements. The
> mobile menu page must follow the design from the chosen template in Figma
> <https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1>
> (e.g., font, colors, images, text, margins). Please change the blue
> background color of your mobile menu page instead used the one provided in
> the Figma template background: #6070FF;. This will make your website
> similar to the original design. 💯 🥇
>
> Nice implementing the design, however, it would be better if you add a
> little bit of blur to your overlay in order to match the Figma design and
> also make a good contrast 🎨 👨🏻‍🎨
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MANYIKAM/Portfolio-setup-and-mobile-first/pull/10#pullrequestreview-1147835896>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYTWFI2GZZKNVIGKUOICDYLWEAIXDANCNFSM6AAAAAARJG4MBM>
> .
> You are receiving this because you were mentioned.Message ID:
> <MANYIKAM/Portfolio-setup-and-mobile-first/pull/10/review/1147835896@
> github.com>
>

2022-10-20 11:12 UTC, brytebee approved these changes
Hi, @MANYIKAM👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- App functions as it should.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

##

###  **Optional Suggestions:**
- N/A

##

Good luck! 🎉 

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 11:19 UTC, merged