Portfolio setup and mobile first two sections added Feature 2
MANYIKAM/Portfolio-setup-and-mobile-first pull request #2
Opened 2022-09-23 22:42 UTC by MANYIKAM

Portfolio setup and mobile first two sections added Feature 2

- Works Section has been added according in respect to the outlined requirements
- Html file has been updated during carrying out this task
- Css file has been also updated as the task was in progress.
- About Myself section has been added with all the stipulated attributes
- flex box and css grid has been used during the implementation of the task.
- The project has been completed

2022-09-23 23:17 UTC, Tadesse-Alemayehu reviewed
Hi @MANYIKAM  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑🛑

![giphy](https://user-images.githubusercontent.com/69077061/192067778-2983f2e8-68d7-406f-b2c1-6aaad569ab62.gif)

- You have submitted a project, that has no linter setup. Please make sure to set up linter and all check are passing before requesting for the next review.
- Also, Kindly watch out for your commit messages also. They should be meaningful.  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-24 12:43 UTC, jerryowusu requested changes
Hi @MANYIKAM 

Your project is looking fantastic so far :star_struck: 

However, I've found some room for improvement that can help you accomplish a more readable/clean code and make your project look professional :sunglasses:

![soclose](https://user-images.githubusercontent.com/65233860/192098497-363ba50e-24c9-4865-b554-19f690973254.gif)

## Highlights
:heavy_check_mark: All linters are passing
:heavy_check_mark: Good commit messages

## Required Changes ♻️
As shown below, your styles are not working due to a typo on line 8 of the index.html. The stylesheet is named `Style.css` _with a capital S_ whiles the link on line 8 of the index.html is referencing `style.css` _with small letter s_. Kindly check and rectify that.

Also, make sure that your design is as close to the figma design as possible since the major aim of this project is to stick to the figma design as much as possible

![Screenshot from 2022-09-24 12-33-29](https://user-images.githubusercontent.com/65233860/192098263-614dd5d3-3647-4999-8e97-8449faa69b94.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 12:43 UTC, jerryowusu commented on index.html
> +            <div class="works-flex-container">
![Screenshot from 2022-09-24 12-11-24](https://user-images.githubusercontent.com/65233860/192097230-5503370a-0c23-4a88-8e25-599798091143.png)

As stated in the project requirement above, you are supposed to create two sections at these stage of the project, one section for the `works/projects` and another section for the `about me`. 
So kindly put all the code from line 30 to 105 in one section (works section) and all the code from line 106 to 134 in another section (about me section). No need to have several sections

2022-09-24 12:43 UTC, jerryowusu commented on index.html
> +            <p class="history">&#x2022; 2015</p>
Please use ul and li for all list items in your project instead of the p tag. This will make your code more readable, clean and up to standard. :+1:

2022-09-24 12:43 UTC, jerryowusu commented on index.html
> +         </ul>
Nice implementation. :1st_place_medal:  Kindly use ul and li tags for all list items just as you did here. :stuck_out_tongue_winking_eye:

2022-09-24 12:43 UTC, jerryowusu commented on index.html
> +          </div> </ul>
No need putting a div between ul and li tags. Kindly remove

2022-09-24 12:43 UTC, jerryowusu commented on Style.css
> +}
kindly use CSS Grid in the main container that contains all of the cards and use Flexbox to lay out an individual card.

2022-09-24 13:08 UTC, MANYIKAM commented on index.html
> +          </div> </ul>
Adjustments has been done as per the instruction

2022-09-24 14:10 UTC, Santiago220991 requested changes
Hi @MANYIKAM , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Highlights
:heavy_check_mark: Follower GitHub flow
:heavy_check_mark: No linter errors.

 ## Required Changes ♻️
There is still an issue. It seems that the CSS is not being loading. Kindly make the changes suggested by the[ last code reviewer](https://github.com/MANYIKAM/Portfolio-setup-and-mobile-first/pull/2#pullrequestreview-1119259274) to load successfully the styling CSS file.

![image](https://user-images.githubusercontent.com/98363075/192102350-dd8c4cc4-9d1e-4534-b9b4-4b1be61f1a24.png)

You should fix this typo in your HTML file inside the `head` tag. Please check the image below. :eyes: 
![image](https://user-images.githubusercontent.com/98363075/192102456-964b65ba-292b-4f5e-abac-3a61ca9a51f5.png)


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 21:21 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @MANYIKAM , I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-24 21:21 UTC, MaganaAsiati commented on index.html
> +             </ul>
- you did a great job by implementing the requirement for the previous reviews but make sure every part is showing properly in your mobile version as you see in the picture below the skills part is not visible kindly fix that :grinning: :grinning: :grinning: 

## your design 

![image](https://user-images.githubusercontent.com/95297251/192118750-2d3bf4e0-5690-4a22-93ae-84e8c9d947cd.png)

## Figma design

![image](https://user-images.githubusercontent.com/95297251/192118786-033cd031-70f7-49e3-88af-2d355880639e.png)

2022-09-24 21:21 UTC, MaganaAsiati commented on index.html
> +    </ul>
- Kindly make sure your icons are arranged correctly  in  your about section  you can add some margin left and bottom to the container of your icons so that it will make your design stick to the Figma design :grin:  :grin:  :grin: 

## your design 

![image](https://user-images.githubusercontent.com/95297251/192119009-af630b68-153d-4256-bfdf-e332f9391ac4.png)

## Figma design

![image](https://user-images.githubusercontent.com/95297251/192119093-9ccc8bf5-0afc-4d34-89dd-515e530c6d40.png)

2022-09-26 06:54 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @MANYIKAM 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your project is professional ✅
- Your repo is professional ✅
- Well structured files ✅
- No Linter errors ✅


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


## Optional suggestions
- [OPTIONAL] I suggest adding the `MIT.md` file to your project 👌, Here is the [Micorverse Template](https://github.com/microverseinc/readme-template/blob/master/MIT.md), and remember to customize it 😉

> The MIT license gives users express permission to reuse code for any purpose, sometimes even if the code is part of proprietary software. As long as users include the original copy of the MIT license in their distribution, they can make any changes or modifications to the code to suit their own needs. 💯

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 06:54 UTC, Bondok6 commented on index.html
> +        <h2><a href="#" class="connect">LET’S CONNECT</a></h2>
- [OPTIONAL] I suggest adding `text-decoration: none`  CSS property to the `connect` class to remove the underlining here to match your Figma design 💯👌

2022-09-26 07:03 UTC, merged

2022-09-26 07:04 UTC, MANYIKAM commented
Portfolio Setup and Mobile First added Additional Sections as follows

1. Works 
   Detailed work experience done in the project
   Brief information about those projects
   The years in which the projects has been done

2. About Myself
   Contains Information which define myself and other languages.