Feature 3
MANYIKAM/Portfolio-setup-and-mobile-first pull request #3
Opened 2022-10-03 19:48 UTC by MANYIKAM

Portfolio setup and mobile first

- Contact Details form has been added  with the following information;
- Description message 
- Full names of the individual
- Contact details inform of email
- Text area for any other desired information to be disclosed prior to submission
- Submission button at the end after capturing all the required fields on the form.

2022-10-03 20:34 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @MANYIKAM :wave:

## Highlights :1st_place_medal:

:heavy_check_mark: Following GitHub Flow
:heavy_check_mark: Following some requirements
:heavy_check_mark: Meaningful commit messages
:heavy_check_mark: Descriptive PR Title
:heavy_check_mark: Descriptive PR Summary

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-03 20:34 UTC, HAMMAS-SALEEM commented on Style.css
> +}
![white-spacing-finish-mobile](https://user-images.githubusercontent.com/93039359/193675509-8aa8de8a-f13b-427d-a4b3-633444da278d.png)


- [ ] Kindly remove `padding: 50px;` to remove the white spacing in your design at the resolution of 375px :blush:

2022-10-03 20:34 UTC, HAMMAS-SALEEM commented on index.html
>               </ul>
![contents](https://user-images.githubusercontent.com/93039359/193676056-2400dcc7-5b6b-414a-bf2c-c78cb81aa39c.png)
![Screenshot from 2022-10-04 01-12-07](https://user-images.githubusercontent.com/93039359/193676120-0e57f75b-a4bc-4113-867e-23cddf5e66f8.png)


- [ ] Kindly make your contents align as you can see in the Figma to make your design professional :+1:

2022-10-03 20:34 UTC, HAMMAS-SALEEM commented on index.html
>               </ul>
### Your Design
![Screenshot from 2022-10-04 00-57-12](https://user-images.githubusercontent.com/93039359/193676618-7e34a161-db48-437d-af41-063ac9c40cd1.png)
### Figma Template

![center](https://user-images.githubusercontent.com/93039359/193676571-35b0c04c-843b-4bce-ace9-aa444c9d059e.png)


Kindly make your contents align in center as you can see in the Figma template :+1: to make your design look professional :blush:

2022-10-03 20:34 UTC, HAMMAS-SALEEM commented on README.md
- [ ] You have added a link to your license file but didn't add a license file in your project. Kindly add an license file using these [guidlines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to make your readme file descriptive :blush:

2022-10-03 23:28 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @MANYIKAM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

_**Kindly check some optional comments I left under the review**_ :pray: 

## Highlights

-  No linter errros. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 
-  Meaningful commit messages. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [OPTIONAL] Kindly look into the list of the tech you used to build a project on each of the projects. Only javascript tech displays. The rest are not showing. Please, look into it and fix it.

### Your Design

![your-design-for-html-css-js](https://user-images.githubusercontent.com/26597432/193703122-cc8edc0f-1786-46a7-b805-b8d3f4b99c8a.png)

### Figma Design

![figma-design-for-html-css-js](https://user-images.githubusercontent.com/26597432/193703150-14190a46-abb3-4700-b8a9-5ad911535de9.png)

- [ ] Your language, frameworks and skills section broke. Maybe when you were trying to make changes required by the previous reviewer. Kindly look into that too and fix them.

### Your Design

![your-lang](https://user-images.githubusercontent.com/26597432/193703415-fd41700f-54b5-433b-b2f2-2f055c4ec642.png)


### Figma Design

![figma-lang](https://user-images.githubusercontent.com/26597432/193703452-7cdf152e-68d6-4693-8418-a4cc945b6f1c.png)

2022-10-04 06:03 UTC, merged

2022-10-04 06:08 UTC, MANYIKAM commented
Mobile first Set-up Portfolio has been completed in line to the provided information

- First Section comprises of the owners details and brief description
- Followed by portfolio projects done entitled Works , which shows almost all the the completed task with reference to years.
- Details of the languages specialized in and their sub divisions
- final the contact details with additional space to leave vital or message the owner.